export const CLIENTS_FETCH = 'CLIENTS_FETCH';
export const CLIENTS_SHOW = 'CLIENTS_SHOW';
export const CLIENTS_REJECT = 'CLIENTS_REJECT';
export const CLIENTS_ADD = 'CLIENTS_ADD';
export const CLIENTS_UPDATE = 'CLIENTS_UPDATE';

